org: scoobies
service: nfc-message
frameworkVersion: "4"

provider:
  name: aws
  stage: prod
  region: ap-south-1
  runtime: nodejs24.x

  environment:
    CURRENT_AWS_REGION: ap-south-1
    TABLE_NAME: messages-data-table
    AWS_USER_PROFILE: serverless-user

  iam: ${file(aws/iam.yaml)}

plugins:
  - serverless-offline

functions:
  textApi:
    handler: src/text/handler.handler
    events:
      - httpApi:
          path: /text/{proxy+}
          method: ANY

resources:
  - ${file(aws/database.yaml)}
